//! Persistence of commands executed through the relay API.
//!
//! The relay's primary persistence today is the append-only audit JSONL log
//! ([`crate::audit`]). That log is for security/ops auditing and is not
//! queryable by account/host in a useful way for "what did I run before?".
//! This module defines the queryable command-history store that the `exec`
//! handler records into and that `GET /api/v1/history` reads from.
//!
//! Like [`crate::executor::RelayExecutor`], the store is defined as a trait
//! and injected into [`crate::server::AppState`]. The app layer provides a
//! SQLite-backed implementation over `rusterm_db::Database`; tests use
//! [`NullHistoryStore`] or [`RecordingHistoryStore`]. This keeps the relay
//! crate decoupled from `rusterm-db` (mirroring how it is decoupled from the
//! SSH backend).
//!
//! # Recording semantics
//!
//! A row is recorded *after* the executor returns, so `exit_code`,
//! `duration_ms`, and `timed_out` reflect the real outcome. Commands rejected
//! *before* reaching the executor (validation, rate limit, host not allowed)
//! are NOT recorded — they never executed, so they aren't "history" the user
//! would want to re-run. A command that reached the executor but failed
//! (SSH connect error, remote exec error) IS recorded with a `None`
//! `exit_code` and `success=false`, so the user can inspect and retry it.

use std::sync::Mutex;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// One executed (or execution-attempted) command, as recorded for later
/// retrieval. Field shape mirrors `rusterm_db::RelayHistoryEntry` but lives
/// in the relay crate so the trait doesn't depend on `rusterm-db`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayHistoryRecord {
    pub id: String,
    pub account: String,
    pub host_id: String,
    pub command: String,
    pub elevated: bool,
    /// `None` when the command ran but no exit code was captured (e.g. SSH
    /// connection dropped). `Some(code)` on normal completion.
    pub exit_code: Option<i32>,
    pub duration_ms: Option<u64>,
    pub timed_out: bool,
    /// RFC3339 UTC timestamp captured at record time.
    pub created_at: String,
    /// Whether the command completed successfully (`exit_code == Some(0)`).
    /// Persisted separately so listings can flag failures without re-deriving
    /// from `exit_code` (which may be `None`).
    pub success: bool,
}

/// Query parameters for [`RelayHistoryStore::list`]. All filters optional.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct HistoryQuery {
    /// Scope to one API account.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account: Option<String>,
    /// Scope to one target host (id or name).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub host_id: Option<String>,
    /// Case-insensitive substring match on `command`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    /// Max entries to return. Server clamps to `[1, 500]`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<usize>,
}

/// Opaque cursor for paginating older entries. Pass the `next_cursor` from
/// one response back as `before` on the next request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HistoryCursor {
    pub created_at: String,
    pub id: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct HistoryPage {
    pub entries: Vec<RelayHistoryRecord>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<HistoryCursor>,
}

/// Persisted by the relay, queryable by the API. Implemented by the app layer
/// (backed by `rusterm_db::Database`); tests use in-memory doubles.
///
/// All methods are best-effort from the caller's perspective: a storage
/// failure must not break command execution, so the `exec` handler records
/// asynchronously and logs (but does not propagate) errors.
#[async_trait]
pub trait RelayHistoryStore: Send + Sync + std::fmt::Debug {
    /// Record one executed command. `created_at` may be generated by the
    /// caller (the handler stamps it with `chrono::Utc::now()`).
    async fn record(&self, record: RelayHistoryRecord) -> anyhow::Result<()>;

    /// Query recorded history, newest first, with optional pagination.
    async fn list(
        &self,
        query: &HistoryQuery,
        before: Option<&HistoryCursor>,
    ) -> anyhow::Result<HistoryPage>;

    /// Delete one entry by id. Returns `true` if a row was removed.
    async fn delete(&self, id: &str) -> anyhow::Result<bool>;
}

/// A `RelayHistoryStore` that discards everything. Used when persistence is
/// unavailable (tests, degraded startup) so the relay still serves `/history`
/// with an empty list rather than panicking.
#[derive(Debug, Default)]
pub struct NullHistoryStore;

#[async_trait]
impl RelayHistoryStore for NullHistoryStore {
    async fn record(&self, _record: RelayHistoryRecord) -> anyhow::Result<()> {
        Ok(())
    }
    async fn list(
        &self,
        _query: &HistoryQuery,
        _before: Option<&HistoryCursor>,
    ) -> anyhow::Result<HistoryPage> {
        Ok(HistoryPage {
            entries: Vec::new(),
            next_cursor: None,
        })
    }
    async fn delete(&self, _id: &str) -> anyhow::Result<bool> {
        Ok(false)
    }
}

/// In-memory `RelayHistoryStore` for tests. Records every `record()` call in
/// insertion order and answers `list`/`delete` against that vector.
#[derive(Debug, Default)]
pub struct RecordingHistoryStore {
    entries: Mutex<Vec<RelayHistoryRecord>>,
}

impl RecordingHistoryStore {
    pub fn new() -> Self {
        Self::default()
    }

    /// Number of recorded entries. For tests that need to observe the async
    /// `record()` write landing.
    pub fn len(&self) -> usize {
        self.entries.lock().unwrap().len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[async_trait]
impl RelayHistoryStore for RecordingHistoryStore {
    async fn record(&self, record: RelayHistoryRecord) -> anyhow::Result<()> {
        self.entries.lock().unwrap().push(record);
        Ok(())
    }

    async fn list(
        &self,
        query: &HistoryQuery,
        before: Option<&HistoryCursor>,
    ) -> anyhow::Result<HistoryPage> {
        let limit = query.limit.unwrap_or(50).clamp(1, 500);
        let entries = self.entries.lock().unwrap();

        // Newest first (insertion order is oldest-first).
        let mut filtered: Vec<RelayHistoryRecord> = entries
            .iter()
            .rev()
            .filter(|e| {
                if let Some(a) = &query.account {
                    if &e.account != a {
                        return false;
                    }
                }
                if let Some(h) = &query.host_id {
                    if &e.host_id != h {
                        return false;
                    }
                }
                if let Some(q) = &query.query {
                    if !e.command.to_lowercase().contains(&q.to_lowercase()) {
                        return false;
                    }
                }
                if let Some(cur) = before {
                    // Strictly older than the cursor (matches DB ordering).
                    if &e.created_at > &cur.created_at {
                        return false;
                    }
                    if &e.created_at == &cur.created_at && &e.id >= &cur.id {
                        return false;
                    }
                }
                true
            })
            .cloned()
            .collect();

        let has_more = filtered.len() > limit;
        if has_more {
            filtered.truncate(limit);
        }
        let next_cursor = has_more.then(|| {
            let last = filtered.last().expect("clamped page limit is non-zero");
            HistoryCursor {
                created_at: last.created_at.clone(),
                id: last.id.clone(),
            }
        });

        Ok(HistoryPage {
            entries: filtered,
            next_cursor,
        })
    }

    async fn delete(&self, id: &str) -> anyhow::Result<bool> {
        let mut entries = self.entries.lock().unwrap();
        let before = entries.len();
        entries.retain(|e| e.id != id);
        Ok(entries.len() < before)
    }
}

/// Generate a fresh history record id and timestamp. Centralised so the
/// `exec` handler doesn't repeat the `uuid`/`chrono` ceremony.
pub fn new_record_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

pub fn now_iso() -> String {
    chrono::Utc::now().to_rfc3339()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rec(
        id: &str,
        account: &str,
        host: &str,
        cmd: &str,
        ts: &str,
        exit: Option<i32>,
    ) -> RelayHistoryRecord {
        RelayHistoryRecord {
            id: id.to_string(),
            account: account.to_string(),
            host_id: host.to_string(),
            command: cmd.to_string(),
            elevated: false,
            exit_code: exit,
            duration_ms: Some(10),
            timed_out: false,
            created_at: ts.to_string(),
            success: exit == Some(0),
        }
    }

    #[tokio::test]
    async fn record_then_list_newest_first() {
        let store = RecordingHistoryStore::new();
        store
            .record(rec(
                "a",
                "ops",
                "h1",
                "uptime",
                "2024-01-01T00:00:00Z",
                Some(0),
            ))
            .await
            .unwrap();
        store
            .record(rec(
                "b",
                "ops",
                "h1",
                "whoami",
                "2024-01-02T00:00:00Z",
                Some(0),
            ))
            .await
            .unwrap();

        let page = store.list(&HistoryQuery::default(), None).await.unwrap();
        assert_eq!(page.entries.len(), 2);
        assert_eq!(page.entries[0].id, "b"); // newest first
        assert!(page.next_cursor.is_none());
    }

    #[tokio::test]
    async fn list_filters_by_account_host_and_query() {
        let store = RecordingHistoryStore::new();
        store
            .record(rec("1", "ops", "h1", "uptime", "t1", Some(0)))
            .await
            .unwrap();
        store
            .record(rec("2", "ops", "h2", "uptime", "t2", Some(0)))
            .await
            .unwrap();
        store
            .record(rec("3", "dev", "h1", "uptime", "t3", Some(0)))
            .await
            .unwrap();
        store
            .record(rec("4", "ops", "h1", "docker ps", "t4", Some(0)))
            .await
            .unwrap();

        let q = HistoryQuery {
            account: Some("ops".into()),
            host_id: Some("h1".into()),
            query: Some("uptime".into()),
            limit: Some(50),
        };
        let page = store.list(&q, None).await.unwrap();
        assert_eq!(page.entries.len(), 1);
        assert_eq!(page.entries[0].id, "1");
    }

    #[tokio::test]
    async fn delete_removes_one_row() {
        let store = RecordingHistoryStore::new();
        store
            .record(rec("x", "ops", "h1", "uptime", "t", Some(0)))
            .await
            .unwrap();
        assert!(store.delete("x").await.unwrap());
        assert!(!store.delete("x").await.unwrap()); // already gone
        let page = store.list(&HistoryQuery::default(), None).await.unwrap();
        assert!(page.entries.is_empty());
    }

    #[tokio::test]
    async fn null_store_is_empty_but_never_errors() {
        let store = NullHistoryStore;
        store
            .record(rec("z", "ops", "h1", "uptime", "t", Some(0)))
            .await
            .unwrap();
        let page = store.list(&HistoryQuery::default(), None).await.unwrap();
        assert!(page.entries.is_empty());
        assert!(!store.delete("z").await.unwrap());
    }
}
